# Generated by Django 5.2.4 on 2025-07-13 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "email",
                    models.EmailField(
                        help_text="Введите Ваш email", max_length=50, unique=True, verbose_name="Электронный адрес"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True, help_text="Введите Ваше Ф.И.О.", max_length=100, null=True, verbose_name="Ф.И.О."
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, help_text="Введите Ваш комментарий", null=True, verbose_name="Комментарий"
                    ),
                ),
            ],
            options={
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
                "ordering": ["email"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "theme",
                    models.CharField(
                        blank=True,
                        help_text="Введите тему Вашего письма",
                        max_length=100,
                        null=True,
                        verbose_name="Тема письма",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="Введите текст Вашего письма", null=True, verbose_name="Тело письма"
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "first_sending",
                    models.DateTimeField(
                        help_text="Введите дату и время первой отправки рассылки",
                        verbose_name="Дата и время первой отправки рассылки",
                    ),
                ),
                (
                    "last_sending",
                    models.DateTimeField(
                        help_text="Введите дату и время последней отправки рассылки",
                        verbose_name="Дата окончания отправки рассылки",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("created", "Создана"), ("started", "Запущена"), ("completed", "Завершена")],
                        default="created",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "clients",
                    models.ManyToManyField(
                        help_text="Укажите Получателей Вашего сообщения",
                        to="newsletter.client",
                        verbose_name="Получатели",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        help_text="Укажите Ваше сообщение",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="newsletter.message",
                        verbose_name="Сообщение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.CreateModel(
            name="AttemptMailing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Введите дату и время первой попытки отправки рассылки",
                        verbose_name="Дата и время первой попытки отправки рассылки",
                    ),
                ),
                (
                    "is_successful",
                    models.BooleanField(
                        default=False, help_text="Укажите, успешной ли была попытка отправки", verbose_name="Успешно"
                    ),
                ),
                (
                    "response",
                    models.TextField(
                        blank=True,
                        help_text="Введите ответ почтового сервера",
                        null=True,
                        verbose_name="Ответ почтового сервера",
                    ),
                ),
                (
                    "mailing",
                    models.ForeignKey(
                        help_text="Укажите текст рассылки",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="newsletter.mailing",
                        verbose_name="Рассылка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка отправки",
                "verbose_name_plural": "Попытки отправки",
            },
        ),
    ]
