# Generated by Django 5.2.4 on 2025-07-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0002_client_owner_mailing_owner_message_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="first_sending",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
