# Generated by Django 5.2.4 on 2025-07-28 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0003_alter_mailing_first_sending"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "ordering": ["email"],
                "permissions": [("view_all_clients", "Can view all clients")],
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
            },
        ),
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [("view_all_mailings", "Can view all mailings")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
