# Generated by Django 5.2.4 on 2025-08-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0004_alter_client_options_alter_mailing_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attemptmailing",
            name="is_successful",
        ),
        migrations.AddField(
            model_name="attemptmailing",
            name="status",
            field=models.CharField(
                choices=[("success", "Успешно"), ("failed", "Не успешно")],
                default="failed",
                max_length=10,
                verbose_name="Статус попытки",
            ),
        ),
        migrations.AlterField(
            model_name="attemptmailing",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Заполняется автоматически при создании попытки",
                verbose_name="Дата и время попытки отправки рассылки",
            ),
        ),
    ]
