# Generated by Django 5.2.4 on 2025-08-05 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0005_remove_attemptmailing_is_successful_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attemptmailing",
            options={
                "permissions": [("view_all_attempts", "Can view all attempts")],
                "verbose_name": "Попытка отправки",
                "verbose_name_plural": "Попытки отправки",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "permissions": [("view_all_messages", "Can view all messages")],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
    ]
