# Generated by Django 5.2.4 on 2025-08-05 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0006_alter_attemptmailing_options_alter_message_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["first_sending"],
                "permissions": [("view_all_mailings", "Can view all mailings")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["owner"],
                "permissions": [("view_all_messages", "Can view all messages")],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
    ]
